# Generated by Django 4.0.3 on 2022-05-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0002_telescope_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telescope',
            name='connected',
        ),
    ]
