# Generated by Django 4.0.3 on 2022-03-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PL', 'Planet'), ('NEO', 'Near-Earth Object'), ('RS', 'Radio Source'), ('DSO', 'Deep-Sky Object')], max_length=100)),
                ('ra', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dec', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
    ]
