# Generated by Django 4.0.3 on 2022-03-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='ra',
            new_name='ra',
        ),
    ]
