# Generated by Django 4.0.3 on 2022-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_c_dec_target_dec_rename_c_ra_target_ra'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='img',
            field=models.ImageField(default=None, upload_to='', null=True, blank=True),
        ),
    ]
