# Generated by Django 4.0.3 on 2022-04-18 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_alter_target_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='target',
            name='ra',
        ),
        migrations.AddField(
            model_name='target',
            name='centre_body',
            field=models.CharField(choices=[('SUN', 'Sun'), ('EARTH', 'Earth'), ('DSO', 'Deep-Sky Object')], default='SUN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='eccentricity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='inclination',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='mean_anomaly',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='perihelion',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='semimajor_axis',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
