# Generated by Django 4.0.3 on 2022-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_remove_target_dec_remove_target_ra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSpaceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PL', 'Planet'), ('NEO', 'Near-Earth Object'), ('RS', 'Radio Source'), ('DSO', 'Deep-Sky Object')], max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('right_acension', models.DecimalField(decimal_places=5, max_digits=10)),
                ('declination', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PL', 'Planet'), ('NEO', 'Near-Earth Object'), ('RS', 'Radio Source'), ('DSO', 'Deep-Sky Object')], max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('semimajor_axis', models.DecimalField(decimal_places=5, max_digits=10)),
                ('eccentricity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('inclination', models.DecimalField(decimal_places=5, max_digits=10)),
                ('perihelion', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mean_anomaly', models.DecimalField(decimal_places=5, max_digits=10)),
                ('init_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
