# Generated by Django 4.0.3 on 2022-04-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_deepspacetarget_solartarget_delete_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepspacetarget',
            old_name='right_acension',
            new_name='right_ascension',
        ),
    ]
