# Generated by Django 4.0.3 on 2022-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_rename_right_acension_deepspacetarget_right_ascension'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepspacetarget',
            name='bayer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deepspacetarget',
            name='magnitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
