# Generated by Django 4.0.3 on 2022-04-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0011_deepspacetarget_bayer_deepspacetarget_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepspacetarget',
            name='bayer',
            field=models.CharField(max_length=100),
        ),
    ]
