# Generated by Django 4.0.3 on 2022-05-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0013_telescope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telescope',
        ),
    ]
